name: 02-Status-handler.yml

on:
  workflow_call:
    inputs:
      projectId:
        type: string
        required: true
      deployId:
        type: string
        required: true
      jobName:
        type: string
        required: false
      status:
        required: false
        type: string
      error:
        required: false
        type: boolean

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:

