name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to release'
        required: true
        type: string
      projectId:
        description: 'Project ID associated'
        required: true
        type: string
      deployId:
        description: 'Deploy ID associated'
        required: true
        type: string

jobs:
  pull-request:
    name: New version PR
    uses: ./.github/workflows/00-PR-pull-request-new-version.yml
    with:
      environment: dev
      new_version: ${{ inputs.version  }}
      projectId: ${{ inputs.projectId }}
      deploymentId: ${{ inputs.deployId }}
    secrets: inherit
