name: Saludo Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to release'
        required: true
        type: string
      projectId:
        description: 'Project ID associated'
        required: true
        type: string
      deployId:
        description: 'Deploy ID associated'
        required: true
        type: string

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "Hola, soy un workflow manual"

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: pr_generated
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "pr_generated", "error": false}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: pr_approved
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "pr_approved", "error": false}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: pr_merged
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "pr_merged", "error": false}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: in_progress
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "in_progress", "error": false}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: new_version_obtained
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "new_version_obtained", "error": false}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: app_build
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "app_build", "error": false}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}

      - name: Esperar 5 segundos antes de continuar
        run: sleep 5

      - name: app_deployed
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"status": "app_deployed", "error": true}' \
            https://us-central1-tintech-crm.cloudfunctions.net/api/deploy/update/${{ inputs.projectId }}/${{ inputs.deployId }}
